HomePage/urls.py
from django.urls import path, include
from . import views
app_name='HomePage'
urlpatterns = [
    path('', views.home, name='home')
]

Ticket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/auth/', include('UserAuth.urls')),
    path('', include('HomePage.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

UserAuth/urls.py
from django.urls import path, include

urlpatterns=[
]

HomePage/models.py
from django.db import models

# Create your models here.

HomePage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "index.html")

UserAuth/views.py
from django.shortcuts import render

# Create your views here.

templates/Base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
          name="viewport">
    <meta content="ie=edge" http-equiv="X-UA-Compatible">
    <title>Tickety | {% block title%}{% endblock %}</title>

    <link href="{% static 'css/bulma.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200;0,6..12,300;0,6..12,400;0,6..12,600;0,6..12,700;0,6..12,900;0,6..12,1000;1,6..12,200;1,6..12,300;1,6..12,400;1,6..12,500;1,6..12,600;1,6..12,700;1,6..12,800;1,6..12,900;1,6..12,1000&display=swap"
          rel="stylesheet">
</head>
<body>

{% include 'navbar.html' %}

{% block content %}
{% endblock %}

{% include 'footer.html' %}
<script src="{% static 'vendor/aos/aos.js' %}"></script>

<script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>


</body>
</html>

templates/footer.html
{% load static %}
<footer class="footer has-background-dark has-text-white">
    <div class="container">
        <div class="columns is-multiline">
            <div class="column is-4">
                <p class="title is-5 has-text-white">Navigation</p>
                <ul class="footer-links">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="column is-4">
                <p class="title is-5 has-text-white">Contact</p>
                <p>Email: contact@example.com</p>
                <p>Phone: +1 234 567 890</p>
            </div>
            <div class="column is-4">
                <p class="title is-5 has-text-white">Follow Us</p>
                <div class="social-icons">
                    <a class="icon-link" href="#"><i class="ri-facebook-fill"></i></a>
                    <a class="icon-link" href="#"><i class="ri-twitter-fill"></i></a>
                    <a class="icon-link" href="#"><i class="ri-instagram-fill"></i></a>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column has-text-centered">
                <hr class="footer-divider">
                <p>&copy; 2023 <b><a href="shihabsaleem.github.io">Shihab.</a></b>All Rights Reserved.</p>
            </div>
        </div>
    </div>
</footer>

templates/index.html
{% extends 'Base.html' %}
{% load static %}


{% block title %}
Home
{% endblock %}

{% block content %}
<div class="container">
    <div class="block">
        <div class="columns is-vcentered">
            <div class="column is-half has-text-centered">
                <div class="home-subtitle">Book Your Special</div>
                <div class="home-title">Event<span>.</span></div>
            </div>
            <div class="column is-half has-text-centered">
                <img alt="Party SVG" src="{% static 'img/party.svg' %}">
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="block">
        <div class="columns ">

            <div class="column is-half has-text-centered">
                <img alt="Party SVG" src="{% static 'img/about.svg' %}">
            </div>

            <div class="column is-half has-text-centered">
                <div class="subtitle is-4">About</div>
                <div class="title is-1">Tickety</div>
                <div class="is-size-6 has-text-left">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer
                    vel mattis
                    justo. Maecenas ante erat, pharetra eu tincidunt sed, fermentum ut est. Donec tempus fringilla erat
                    vel hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vel ligula sed neque
                    fringilla tincidunt. Proin quis nibh vitae lectus consectetur viverra. In placerat leo et justo
                    rhoncus, et suscipit sapien mattis. Fusce pulvinar varius quam, vitae egestas elit malesuada a.
                    Quisque eu dictum felis. Maecenas bibendum mi ut odio placerat, sed varius mi faucibus. Fusce
                    ultricies porttitor risus ac ultricies.
                    </br>
                    </br>
                    In finibus egestas elit vitae bibendum. Duis sit amet ipsum elementum, congue nulla eget, blandit
                    ligula. In hac habitasse platea dictumst. Ut aliquam sollicitudin odio eu iaculis. Mauris ultricies
                    lorem eu mauris molestie, quis sollicitudin elit congue. Phasellus a semper mauris. Etiam fermentum,
                    metus eget commodo pretium, libero risus convallis velit, ut condimentum ligula ante euismod dui.
                    Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus ac pellentesque risus, ut
                    pulvinar justo. Aliquam lacinia vulputate libero vel venenatis. Pellentesque fermentum, massa ut
                    aliquet suscipit, lectus orci iaculis leo, ac commodo ligula mauris ut eros. In molestie vehicula
                    nisi in ullamcorper. Mauris nec ipsum ac justo malesuada rutrum ac id dolor. Aenean id lacus lorem.
                    Fusce sagittis lorem enim, sed aliquet augue lobortis posuere.
                </div>
            </div>

        </div>
    </div>
</div>

<div class="container">
    <div class="block">
        <div class="column is-full has-text-centered">
            <div class="subtitle is-4">Upcoming</div>
            <div class="title is-1">Events</div>
        </div>
        <div class="column is-full">
            <!-- Swiper -->
            <div class="swiper mySwiper">
                <div class="swiper-wrapper">
                    <div class="swiper-slide is-half">

                        <div class="card">
                            <div class="card-image">
                                <img alt="Placeholder image" src="{% static 'img/party.svg' %}">
                            </div>
                        </div>

                    </div>
                    <div class="swiper-slide is-half">
                        <div class="card">
                            <div class="card-image">
                                <img alt="Placeholder image" src="{% static 'img/party.svg' %}">
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide is-half">
                        <div class="card">
                            <div class="card-image">
                                <img alt="Placeholder image" src="{% static 'img/party.svg' %}">
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide is-half">
                        <div class="card">
                            <div class="card-image">
                                <img alt="Placeholder image" src="{% static 'img/party.svg' %}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="swiper-pagination"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/navbar.html
{% load static %}


<nav aria-label="main navigation" class="navbar" role="navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'HomePage:home' %}">
            <img height="28" src="{% static 'img/logo.png' %}" width="112">
        </a>

        <a aria-expanded="false" aria-label="menu" class="navbar-burger" data-target="navbarBasicExample" role="button">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div class="navbar-menu" id="navbarBasicExample">
        <div class="navbar-start">
            <a class="navbar-item" href="{% url 'HomePage:home' %}">
                Home
            </a>

            <a class="navbar-item">
                Documentation
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    More
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item">
                        About
                    </a>
                    <a class="navbar-item">
                        Jobs
                    </a>
                    <a class="navbar-item">
                        Contact
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item">
                        Report an issue
                    </a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <a class="button is-primary">Sign up</a>
                    <a class="button is-primary">Log in</a>
                </div>
            </div>
        </div>
    </div>
</nav>